spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST:localhost}:3306/springdb
    username: root
    password: root
  jpa:
    show-sql: true
  application:
    name: emp-service
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: http://localhost:9411
    
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}