server:
  port: 8180
  
spring:
  application:
    name: hr-service
  zipkin:
    enabled: true
    discovery-client-enabled: true
    base-url: http://localhost:9411
    
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j.circuitbreaker:
    instances:
         hr-app-finder:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 10
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            automaticTransitionFromOpenToHalfOpenEnabled: true
            


management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true